### ISSUE TITLE
Sudah mendekati akhir semester ganjil, tapi kok belum dirilis ?

### ISSUE THREAD

**Issue by imammh** [eraporsmk/erapor6#1]
Yth. Bapak/Ibu Pengembang

Ini sudah mendekati akhir semester ganjil
Tapi kenapa sampai saat ini kok belum ada kabar terkait rilis versi 6,
Sedangkan versi 5 juga tidak ada update semester juga sepertinya ?

Mohon penjelasannya.

**Comment by cahyadiwily** [comment]
betul, mohon kepastian terkait update erapor versi 6

**Comment by imammh** [comment]
Sudah dirilis pada 15 November 2022

Semoga kedepannya bisa rilis lebih awal jika ada update dan sebagainya.

Terimakasih.

**Comment by Didik-Suryanto** [comment]
setuju ...
sudah akhir bulan november, belum ada rilis resmi,
masih belum bisa cetak biodata siswa kelas X dan sampul rapor juga ...
