### ISSUE TITLE
Cetak/Print Rapor Akademik Terpotong

### ISSUE THREAD

**Issue by restupamuji** [eraporsmk/erapor6#101]
Beberapa Kelas (Hampir kebanyakan) terpotong saat cetak rapor akademik, beserta footer erapor.
Mohon solusinya para master

![image](https://user-images.githubusercontent.com/73053059/206940202-e180eb96-ed09-4b38-b62a-164c313d6907.png)

Aplikasi yang sedang dipakai:
1. Operating System: Windows Server
2. Versi Aplikasi: 6.0.1
3. Versi Database: 5.0.2

**Comment by idSarmen** [comment]
kasusnya sama,
sudahkah ada solusi?

**Comment by restupamuji** [comment]
> 

Belum pak

**Comment by imammh** [comment]
> Beberapa Kelas (Hampir kebanyakan) terpotong saat cetak rapor akademik, beserta footer erapor. Mohon solusinya para master
> 
> ![image](https://user-images.githubusercontent.com/73053059/206940202-e180eb96-ed09-4b38-b62a-164c313d6907.png)
> 
> Aplikasi yang sedang dipakai:
> 
>     1. Operating System: Windows Server
> 
>     2. Versi Aplikasi: 6.0.1
> 
>     3. Versi Database: 5.0.2

Kami juga mengalami hal yang sama

**Comment by irfansobo2022** [comment]
kami juga
![potong](https://user-images.githubusercontent.com/118572243/207465145-92b80b01-e4d6-4e1e-b78a-e4b35bb6b142.png)

**Comment by f4lcon16** [comment]
Apakah Sudah Ada Solusi ??

**Comment by ibrahimwahyus** [comment]
Belum ada solusikah?? DI versi 6.0.2 juga masih belum betul nii masih terpotong..
waktu sudah mepet...

**Comment by eraporsmk** [comment]
Silahkan update ke versi 6.0.3

Terima kasih
