### ISSUE TITLE
Nama siswa tidak terurut secara ascending 

### ISSUE THREAD

**Issue by ariemusbandi** [eraporsmk/erapor6#102]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Ubuntu 20.4
2. Versi Aplikasi: 6.0.1
3. Versi Database: 5.0.2

Mohon diperbaiki nama siswa tidak terurut secara ascending dengan benar
<img width="373" alt="nama siswa tidak urutt" src="https://user-images.githubusercontent.com/49692660/206947436-9f2c928d-2f9f-4b32-ac84-edab7b17fa05.png">

**Comment by eraporsmk** [comment]
Bisa di informasikan ini ada di menu apa bapak?
