### ISSUE TITLE
unduh leger kelas 12 tidak muncul diakun wakakur

### ISSUE THREAD

**Issue by hid0** [eraporsmk/erapor6#108]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Linux Ubuntu 18.04
2. Versi Aplikasi: 6.0.1
3. Versi Database: 5.0.2

![image](https://user-images.githubusercontent.com/20245892/207112823-eb81df6a-35f7-49a8-887f-543adc15b502.png)

### **sementara kelas 10 dan 11 muncul**
![image](https://user-images.githubusercontent.com/20245892/207112956-bf94bdb3-5c5c-4c1f-9667-2188e03a96d1.png)
![image](https://user-images.githubusercontent.com/20245892/207113074-ee662a81-4990-4505-a4b9-faca77d23061.png)

**Comment by eraporsmk** [comment]
Silahkan di update ke versi 6.0.3

Terima kasih
