### ISSUE TITLE
Registrasi Erapor v6.0 gagal

### ISSUE THREAD

**Issue by Farasya32** [eraporsmk/erapor6#109]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Windows 10 Pro
2. Versi Aplikasi: Erapor SMK V6

Setelah erapor SMK di install pada saat melakukan registrasi muncul notifikasi error 404 halaman tidak ditemukan. Bagaimana mengatasinya?

**Comment by eraporsmk** [comment]
Pertanyaan yang sama sudah terjawab di #124
