### ISSUE TITLE
Cetak rapor untuk pd yang sudah keluar

### ISSUE THREAD

**Issue by firemansaja** [eraporsmk/erapor6#11]
barangkali bisa bisa ditambahkan pak/bu, agar peserta didik yang sudah keluar supaya masih bisa dicetak rapornya

**Comment by imammh** [comment]
kalau di versi sebelumnya, saya bisa cetak, 
dengan pindah ke tiap-tiap semester sebelumnya

**Comment by firemansaja** [comment]
di versi 6 saya coba belum bisa
