### ISSUE TITLE
migration db di vps

### ISSUE THREAD

**Issue by ndiptra** [eraporsmk/erapor6#110]
![image](https://user-images.githubusercontent.com/117172868/207304153-be53ffd6-74e8-473e-8cdb-e12f1f893b2c.png)

**Comment by janglapuk** [comment]
Apakah error karena menggunakan database MySQL? Jika ya, gunakan PostgreSQL saja.

Error 1059 biasanya hanya terjadi di MySQL.

**Comment by eraporsmk** [comment]
Aplikasi eRaporSMK harus menggunakan database PostgreSQL.

Terima kasih
