### ISSUE TITLE
Error Simpan Capaian Kompetensi

### ISSUE THREAD

**Issue by Irham82** [eraporsmk/erapor6#113]
![11](https://user-images.githubusercontent.com/68411024/207489478-c98cb903-5d7e-4562-b6c7-113db1a05684.jpg)
Mohon Solusinya Capaian Kompetensi hanya Sampai Maksimal 100 Karakter

**Comment by eraporsmk** [comment]
Saat ini sudah dibuka kembali (tidak ada batasan maksimal)

Terima kasih...
