### ISSUE TITLE
Mapping Pembelajaran

### ISSUE THREAD

**Issue by firemansaja** [eraporsmk/erapor6#12]
pada saat menyimpan mapping pembelajaran, pembelajaran rombel lain yang sudah disimpan sebelumnya menjadi kosong/berantakan lagi
![Untitled](https://user-images.githubusercontent.com/95914277/202966568-528599dd-2c15-43d2-80f0-c5c0a3b57df2.png)

**Comment by smkronas** [comment]
permasalahan yg sama pada sekolah kami, guru pengajar dan kelompok mapelnya berubah sendiri

**Comment by ozonerik** [comment]
coba pake perintah 'git pull origin main' dulu, biar update dengan pembaharuan terbaru yg ada di github

**Comment by smkronas** [comment]
tetap acak, tidak ada perubahan setelah 'git pull origin main'

**Comment by ariemusbandi** [comment]
itu harus di refresh dulu

**Comment by ozonerik** [comment]
sudah solved pa masalahnya ?

**Comment by firemansaja** [comment]
belum

**Comment by smkpgriciawigebang** [comment]
![mapil tidak ada](https://user-images.githubusercontent.com/96274925/203707270-6cf2b602-6661-4e95-bc52-5845d9c6d208.PNG)
mohon solusi tidak bisa maping mapel pilihan, padahal di dapodik sudah semua diisi, sinkorn mapel sudah lengkap

**Comment by imammh** [comment]
@smkpgriciawigebang Dapodiknya coba di sinkron ulang
