### ISSUE TITLE
[BUG] Progres Penilaian Tahun Pelajaran 2022/2023 Ganjil

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#121]
Data yang ditampilkan semuanya, seharusnya data yang ditampilan sesuai dengan tahun ajaran yang sekarang / yang dipilih.
![image](https://user-images.githubusercontent.com/49719997/208214905-c1f648e5-c182-4dc1-8acf-7ee5e7603877.png)
![image](https://user-images.githubusercontent.com/49719997/208214924-a57beffb-3bf6-4cef-8666-75afd325c532.png)

**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Ubuntu
2. Versi Aplikasi:  6.0.2 commit per 17-12-2022
3. Versi Database: 5.0.2

**Comment by eraporsmk** [comment]
Sudah diperbaiki, silahkan git pull kembali

Terima kasih...
