### ISSUE TITLE
[bug] di erapor v 6.0.3 hilangnya opsi pilihan jumlah karakter deskripsi capaian pembelajaran di pengaturan umum

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#122]
hilangnya opsi pilihan jumlah karakter deskripsi capaian pembelajaran

![image](https://user-images.githubusercontent.com/49719997/208238108-520fefe0-49f8-4477-b1c9-98a492c40a93.png)

**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System:  ubuntu
2. Versi Aplikasi: 6.0.3
3. Versi Database: 5..0.2

**Comment by merzakk** [comment]
Bukannya itu memang di hilangkan za pak, karena banyak guru yang mengeluh pembatasan jumlah karakter
