### ISSUE TITLE
Tidak bisa register

### ISSUE THREAD

**Issue by irulhuda983** [eraporsmk/erapor6#124]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai: erapor6.0.3
1. Operating System: linux
2. Versi Aplikasi: 6.0.3
3. Versi Database: 5.05

**Comment by imammh** [comment]
server pusat gangguan

**Comment by DerDjava** [comment]
Sama gak bisa registrasi. 404 Not Found
![registrasi](https://user-images.githubusercontent.com/5112878/208307674-1c95ae3b-b0ed-4e9a-b62c-24c2feda9d2c.png)

**Comment by eraporsmk** [comment]
Untuk pengguna baru yang belum pernah memakai aplikasi eRapor:
- pengguna linux: Silahkan lakukan migrate & seed ulang
- pengguna windows: Silahkan lakukan install ulang aplikasi

Terima kasih...
