### ISSUE TITLE
Tarik data dari dapodik (DATA DARI DAPODIK ADA YANG BELUM MASUK ERAPOR)

### ISSUE THREAD

**Issue by Kunyank** [eraporsmk/erapor6#125]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai: 
1. Operating System: WINDOWS 11
2. Versi Aplikasi: 6.0.3
3. Versi Database: 5.0.3

**Comment by imammh** [comment]
server pusat gangguan

**Comment by Kunyank** [comment]
Kapan server pusat stabil lagi?

Pada tanggal Min, 18 Des 2022 07.27, imammh ***@***.***>
menulis:

**Comment by imammh** [comment]
sudah OK lagi sejak siang tadi,
jika sudah terselesaikan, mohon berkenan close with coment
