### ISSUE TITLE
Deskripsi Capaian Pembelajaran tidak muncul otomatis jika menggunakan pengisian nilai dengan cara upload template nilai akhir

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#126]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: ubuntu
2. Versi Aplikasi: 6.0.3
3. Versi Database:5.0.2

**Comment by eraporsmk** [comment]
Deskripsi Capaian Kompetensi memang dibuat tidak otomatis, baik input nilai melalui template atau input manual.
Untuk menampilkan Capaian Kompetensi di cetak rapor, Silahkan masuk ke menu Nilai Akademik => Capaian Kompetensi
Guru bisa mengedit atau tetap membiarkan seperti apa yang tertera, kemudian klik tombol Simpan

Terima kasih...
