### ISSUE TITLE
Deskripsi Capaian Kompetensi Tidak Muncul di Rapor 

### ISSUE THREAD

**Issue by dismanska** [eraporsmk/erapor6#129]
**Request kepada pengembang eRapor : 
Jika pada input nilai akhir, siswa diceklis pada kolom tidak tercapai untuk semua CP nya, seharusnya tetap muncul di deskripsi saat akan cetak rapor. Hal ini sebagai informasi juga kepada orang tua terkait perkembangan pembelajaran putra putrinya. Jangan dibuat menjadi tidak muncul / kosong, karena bagaimanapun, tetap perlu ada deskripsi informasi capaian yang muncul di cetak rapor siswa**

Aplikasi yang sedang dipakai:
1. Operating System: Windows
2. Versi Aplikasi: 6.0.3
3. Versi Database: 5.0.3

**Comment by eraporsmk** [comment]
Sudah diperbaiki, silahkan di git pull

Terima kasih

**Comment by dismanska** [comment]
terima kasih banyak admin
