### ISSUE TITLE
Kelompok Mata Pelajaran

### ISSUE THREAD

**Issue by ariemusbandi** [eraporsmk/erapor6#13]
Saat melakukan maping Pembelajaran khusus untuk Kurikulum merdeka pilihan kelompok mata pelajaran tidak munclul, ini disebabkan tidak adannya data kelompok mata pelajaran untuk kurikulum mereka (2022) pada tabel ref.kelompok, mohon untuk segera di tetapkan keompok mata pelajaran (Kelompok Umum, Kelompok Kejuruan, Penguatan Profil Pelajar Pancasila

**Comment by ariemusbandi** [comment]
Saya sudah melakukan mamping pembelajaran untuk kurikulum merdeka, tetapi tidak terdapat pilihan kelompok mata pelajaran, akibatnya ketika login menggunakan akun guru mata pelajaram kurikulum merdeka tidak muncul. mohon solusinya
<img width="960" alt="Screenshot 2022-11-24 062158" src="https://user-images.githubusercontent.com/49692660/203662777-31f34ac7-97c4-4518-a601-3ddc42a03e1b.png">
<img width="960" alt="Screenshot 2022-11-24 062244" src="https://user-images.githubusercontent.com/49692660/203662783-a0b19a47-c8a0-465d-9e8a-1010d94ae63f.png">

**Comment by imammh** [comment]
@ariemusbandi sudah lakukan git pull hari ini ?

**Comment by ariemusbandi** [comment]
> @ariemusbandi sudah lakukan git pull hari ini ?

sudah berkali2, malah saya coba clone ulang, dan membuat database ulang

**Comment by ariemusbandi** [comment]
Saya coba lihat di tabel ref.kelompok, ternyata di situ tidak dada untuk kurikulum 2022

**Comment by ariemusbandi** [comment]
Solve, ternyata harus di php artisan erapor:update
