### ISSUE TITLE
Data Ekstrakurikuler Tidak muncul

### ISSUE THREAD

**Issue by impeesa182** [eraporsmk/erapor6#131]
Setiap Syncron data eskul tetap 0
![image](https://user-images.githubusercontent.com/54379803/208317591-2bdf20d8-bae4-4df6-8c70-d677863e1b83.png)

Operating System: Windows 10 Enterprise build 18363
Versi Aplikasi: 6.0.3
Versi Database: 5.0.3

**Comment by eraporsmk** [comment]
Bisa di screenshot laman sinkronisasi di aplikasi eRapornya bapak?

**Comment by impeesa182** [comment]
![image](https://user-images.githubusercontent.com/54379803/208376253-f12ddda3-5f13-46db-93e3-0d8d4ce942ec.png)

**Comment by SMKPHT** [comment]
saya juga sama, tidak bisa ambil data ekstrakurikuler

**Comment by impeesa182** [comment]
ok sdah bisa
