### ISSUE TITLE
Tarik data dari dapodik tidak bisa lagi

### ISSUE THREAD

**Issue by Kunyank** [eraporsmk/erapor6#134]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: windows 11
2. Versi Aplikasi: 6.0.3
3. Versi Database:5.0.3

**Comment by siti-maslamah** [comment]
Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan
