### ISSUE TITLE
Upload nilai dengan template nilai KD

### ISSUE THREAD

**Issue by irfansobo2022** [eraporsmk/erapor6#14]
Terjadi error saat upload  nilai dengan template nilai KD
![upload](https://user-images.githubusercontent.com/118572243/203141796-35099347-4991-448e-a9f9-71b73863f779.png)

**Comment by imammh** [comment]
Jenis file excelnya apakah sudah .xlsx ?

**Comment by irfansobo2022** [comment]
![ketrampln](https://user-images.githubusercontent.com/118572243/203472073-64e099b0-3bfd-43fe-85da-6a65c487bbef.png)

**Comment by smkronas** [comment]
setiap upload selalu muncul eror server

**Comment by imammh** [comment]
**Sudah bisa unggah, tapi belum bisa masuk keseluruhan nilainya.**
Mohon dicek ulang @masadi 
Terimakasih.

![gambar](https://user-images.githubusercontent.com/102570358/203826792-01f437bf-71a2-4694-8259-bfcfdcd0f43c.png)

sudah saya lakukan
```
git pull origin main
php artisan config:cache
php artisan view:cache
php artisan route:cache
```

**Comment by irfansobo2022** [comment]
ya sama baik di Pengetahuan dan Keterampilan

**Comment by eraporsmk** [comment]
Sementara di tutup karena belum ada tindak lanjut

Terima kasih
