### ISSUE TITLE
Gagal Sincron dengan dapodik

### ISSUE THREAD

**Issue by Kunyank** [eraporsmk/erapor6#143]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: windows 11
2. Versi Aplikasi: 6.0.3
3. Versi Database:5.0.3
![image](https://user-images.githubusercontent.com/120827421/208556093-de3e30a4-10c9-4158-8451-323eb6dcbd35.png)

**Comment by redisetiansah** [comment]
Sama

**Comment by xeizer** [comment]
Server lagi ridak respon

![image](https://user-images.githubusercontent.com/33388453/208584413-8b20ea8f-736c-4ed1-93d3-37a2ea4382d9.png)

**Comment by Kunyank** [comment]
Masih pakek versi 6.0.0?

**Comment by imammh** [comment]
silahkan dicoba lagi
kalau sudah solved, mohon di close

**Comment by eraporsmk** [comment]
Jika respon server 403, silahkan cek kembali email akun administratornya.
Pastikan emailnya menggunakan akun dapodik aktif.
