### ISSUE TITLE
Eskul ada yang double dan deskripsinya ngaco

### ISSUE THREAD

**Issue by mahrubi23** [eraporsmk/erapor6#145]
![bug erapor ekskul v1](https://user-images.githubusercontent.com/108577830/208570600-f2037df7-45f4-4afd-965d-9d71004e9c13.PNG)

**Eskul ada yang double dan deskripsinya ngaco**
Aplikasi yang sedang dipakai:
1. Operating System: Win 10
2. Versi Aplikasi: 6.0.3
3. Versi Database: 5.0.3

**Comment by Kunyank** [comment]
Kumer Osis jadi ekstra iya?

**Comment by imammh** [comment]
coba reset penilaian ekstra

**Comment by eraporsmk** [comment]
Sudah dibenahi di versi 6.0.5
