### ISSUE TITLE
Kolom Checklist CP terceklis pada bagian tercapai dan tidak tercapai

### ISSUE THREAD

**Issue by dismanska** [eraporsmk/erapor6#148]
**Mohon infonya, terjadi bug seperti foto dibawah. pada menu input nilai akhir, beberapa siswa terchecklist pada kolom tercapai dan tidak tercapai, di unchecklist secara manual tidak bisa. sudah memakai template excel pun tetap tidak berubah. mohon sarannya**
Aplikasi yang sedang dipakai:
1. Operating System: Windows
2. Versi Aplikasi: 6.0.3
3. Versi Database: 5.0.3
<img width="697" alt="bug erapor" src="https://user-images.githubusercontent.com/120947091/208590162-ba787bb5-2447-43bf-a3a0-7099d7f57bdf.png">
<img width="707" alt="bug 2" src="https://user-images.githubusercontent.com/120947091/208590167-3910d761-27e8-4672-b802-5010b00f7530.png">

**Comment by imammh** [comment]
upload ulang template nilai akhir
pada bagian sheet kedua isi 0 pada bagian yang tidak ingin di centang

**Comment by dismanska** [comment]
> upload ulang template nilai akhir pada bagian sheet kedua isi 0 pada bagian yang tidak ingin di centang

sudah solved pak, ternyata di templatenya harus dikosongkan dulu semua angkanya (jangan ditulis angka 1 atau 0), kemudian di upload. maka kolom ceklisan menjadi kosong kembali

**Comment by dismanska** [comment]
problem solved, terima kasih admin
