### ISSUE TITLE
Cetak Rapor Kurikulum Merdeka Error

### ISSUE THREAD

**Issue by radityaWahyu** [eraporsmk/erapor6#15]
Ketika mencetak rapor kurikulum merdeka error empty response
![Screen Shot 2022-11-22 at 14 17 12](https://user-images.githubusercontent.com/53686686/203250015-644ee150-0da2-4ee3-bf1d-869a4ccac0ab.png)

**Comment by ozonerik** [comment]
coba permission dari storage nya, atau php_max_execution_time nya dibesarin, 
coba juga git pull origin main

**Comment by eraporsmk** [comment]
Jalankan composer update

**Comment by untungramdani** [comment]
Untuk tingkat SMP bagaimana yaa apakah ada atau bisa ?

**Comment by smkpgriciawigebang** [comment]
![WhatsApp Image 2022-12-06 at 09 32 10](https://user-images.githubusercontent.com/96274925/206605479-671725be-4bbd-49ff-85d5-3eda6353e46b.jpeg)
mohon solusi untuk mapel pilihan kelas XI saat cetak rapot no urut mapel pilihannya sama, nilai mapel pilihan pertama tertimpa dengan nilai mapel pilihan kedua yang baru diinput
