### ISSUE TITLE
#ask

### ISSUE THREAD

**Issue by merzakk** [eraporsmk/erapor6#150]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: 
2. Versi Aplikasi: 
3. Versi Database:

Mending singkron dengan dapodik local min, kalau singkron dengan dapodik direktorat banyak tidak tersambungnya

**Comment by imammh** [comment]
sudah ok sekarang
