### ISSUE TITLE
Apa kabar Server pusat?masih belum bisa tarik data nih dari dapodik

### ISSUE THREAD

**Issue by Kunyank** [eraporsmk/erapor6#151]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: WINDOWS 11
2. Versi Aplikasi: 6.0.3
3. Versi Database: 5.0.3
![image](https://user-images.githubusercontent.com/120827421/208764374-da86ba9f-6cc8-4165-a13f-6d7ff5bcdc32.png)

**Comment by khairinalbimawi** [comment]
masih belum bisa tarik data Dapodik
