### ISSUE TITLE
Anggota Ekskul kosong

### ISSUE THREAD

**Issue by yayanch** [eraporsmk/erapor6#155]
sudah update dapodik dan sinkron di aplikasi erapor. cuma daftar anggota beberapa ekskul tidak muncul. 

![image](https://user-images.githubusercontent.com/62583586/209146348-7faaad49-b25c-49c5-858b-2c3141766a9c.png)

![image](https://user-images.githubusercontent.com/62583586/209146439-77e7f2da-dbfd-453d-9ccc-b14dc9aebc48.png)

Mohon perbaikannya. Terima Kasih

**Comment by eraporsmk** [comment]
Menurut jumlah data di screenshot di atas, jumlah anggota ekskul Senin Musik jumlahnya 0.
Silahkan klik tombol sinkronisasi untuk mengambil data anggota ekskul dari dapodik.
Jika masih tetap 0 setelah di sinkronisasi, silahkan cek kembali isian dapodiknya.

Terima kasih

**Comment by yayanch** [comment]
Done..makasih banyak..
