### ISSUE TITLE
Di terima di kelas tidak berubah

### ISSUE THREAD

**Issue by merzakk** [eraporsmk/erapor6#159]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: 
2. Versi Aplikasi: 
3. Versi Database:
![Untitled](https://user-images.githubusercontent.com/119062563/209249648-5cd9f9ca-a3b4-41e2-b914-48f4b0745099.jpg)

Di terima di kelas tidak berubah meski sudah di singkron beberapa kali

**Comment by eraporsmk** [comment]
Jika tidak sesuai, silahkan edit manual.
Terima kasih
