### ISSUE TITLE
Menu Penilaian Projek untuk P5 tidak muncul

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#16]
Menu Penilaian Projek untuk P5 tidak muncul, dan bagaimana cara menambahkan hak akses untuk kordinator P5, karena hasil sinkoronisasi erapor, tidak memuncul guru dengan hak akses sebagai kordinator P5.

**Comment by firemansaja** [comment]
didapodiknya sudah ditambah Tugas Tambahan sebagai Koordinator P5 Pak ?

**Comment by ozonerik** [comment]
sudah

**Comment by ozonerik** [comment]
![image](https://user-images.githubusercontent.com/49719997/203319248-918f9a9f-d641-41b8-b316-c47aff14f153.png)

**Comment by ozonerik** [comment]
di dapodik sudah diset tugas tambahan kordinator P5, tetapi hak akses tetap tidak terdetek kordinator P5, 
![image](https://user-images.githubusercontent.com/49719997/203319518-1ba80ccc-f04b-4227-89a0-d62c243b706b.png)

**Comment by eraporsmk** [comment]
Di pembelajaran Dapodik, tambah juga mapel P5 dan di ampu oleh koordinator P5 nya, jangan lupa tema P5 nya juga ditambah di Dapodik

Terima kasih

**Comment by ozonerik** [comment]
![image](https://user-images.githubusercontent.com/49719997/203733872-3804ac2a-48c0-4da8-8c30-d2b6774d4c5d.png)

**Comment by ozonerik** [comment]
> Di pembelajaran Dapodik, tambah juga mapel P5 dan di ampu oleh koordinator P5 nya, jangan lupa tema P5 nya juga ditambah di Dapodik
> 
> Terima kasih

untuk penambahan tema p5 di dapodiknya ada di menu apa pa ?

**Comment by imammh** [comment]
> > Di pembelajaran Dapodik, tambah juga mapel P5 dan di ampu oleh koordinator P5 nya, jangan lupa tema P5 nya juga ditambah di Dapodik
> > Terima kasih
> 
> untuk penambahan tema p5 di dapodiknya ada di menu apa pa ?

1). Tambahkan tugas tambahan pada guru-guru yang mendapatkan tugas sebagai koordinator P5 di Dapodik
2). Buka pembelajaran Rombel dan tambahkan tema dan jam nya, pilih guru koordinatornya juga

Selengkapnya bisa lihat panduan-panduan di youtube 
Contoh https://www.youtube.com/watch?v=v8BUsESkGJM

Jika sudah terselesaikan, silahkan di close tread nya
