### ISSUE TITLE
Jumlah ekskul tidak sama dengan dapodik

### ISSUE THREAD

**Issue by Rzlhryt** [eraporsmk/erapor6#161]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System:  win 11
2. Versi Aplikasi: 6.0.3
3. Versi Database: 5.0.3

Jumlah ekstrakulikuler tidak sama dengan yg ada di dapodik, melakukan sync ulang hasilnya tetap sama

**Comment by masadi** [comment]
Jumlah ekskulnya apa anggota ekskulnya pak?

**Comment by Rzlhryt** [comment]
Jumlah ekskulnya pak, di dapodik ada 9, di erapor hanya 7, jadi ada ekskul yg tidak ketarik ke erapor

**Comment by masadi** [comment]
kapan terakhir sinkron dapodiknya?
mungkin menunggu dulu 1x24 jam pak

**Comment by Rzlhryt** [comment]
Sore ini pak, cb ditunggu 1x24 jam dulu berarti pak
