### ISSUE TITLE
Tampilan Beranda Siswa Masih Kosong

### ISSUE THREAD

**Issue by Bahriannoor** [eraporsmk/erapor6#163]
Mohon untuk di tampilkan seperti versi sebelumnya
terima kasih

**Comment by imammh** [comment]
mohon disertakan tangkapan layar tampilan yang dimaksud

**Comment by impeesa182** [comment]
kaya gini tampilan siswa
![image](https://user-images.githubusercontent.com/54379803/210185300-7d66bf90-b46a-4646-86d0-4137a1605fbb.png)

**Comment by eraporsmk** [comment]
Di versi 6x, akses siswa belum dibuka. Nanti akan dibuka di versi 7x
