### ISSUE TITLE
e-Rapor SMK K13

### ISSUE THREAD

**Issue by restupamuji** [eraporsmk/erapor6#165]
Apakah e-Rapor SMK satu aplikasi untuk K13 dengan Kurmer ?

**Comment by restupamuji** [comment]
![image](https://user-images.githubusercontent.com/73053059/209669102-b691207d-22f3-410b-acd6-61b14b25a593.png)
![image](https://user-images.githubusercontent.com/73053059/209669130-85151134-3591-4980-ac7e-35a3d5e3bc77.png)

Soalnya tidak ada menu Kurikulum K13

**Comment by imammh** [comment]
Silahkan baca dan pahami

[Pedoman Pembelajaran dan Asesmen Kurikulum 2013](https://drive.google.com/file/d/19tP2LIclhq0a5phMsBnlVQuzdZynPeRV/view?usp=share_link)
