### ISSUE TITLE
Terjadi BUG saat P5

### ISSUE THREAD

**Issue by merzakk** [eraporsmk/erapor6#166]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: windows 10
2. Versi Aplikasi: 
3. Versi Database:
![2](https://user-images.githubusercontent.com/119062563/209762113-c7bd2592-dd01-4bd3-b1ed-06564ec341ea.jpg)
 ketika Penginputan

![1](https://user-images.githubusercontent.com/119062563/209762253-53503385-cd8b-4ee8-af1b-702c662337e4.png)
ketika cetak, muncul kolom baru

**Comment by masadi** [comment]
Duplikasi #154
