### ISSUE TITLE
tidak bisa update ke 6.0.2

### ISSUE THREAD

**Issue by tomyhartanto** [eraporsmk/erapor6#170]
![gagal update 602](https://user-images.githubusercontent.com/121843674/210299745-4d563be4-5624-4a11-83f4-bae89be872b0.png)
saya mau update dari 601 ke 602, tapi notif updatenya masih 601. itu knp ya

**Comment by WARDI-NURYANTO** [comment]
ambil file master-main yang 6.0.3, copykan filenya yang didownload dari github terus di dataweb lama replace, sama2 belajar yah pak mohon maaf lancang

**Comment by awanzsync** [comment]
saya juga persis kayak gitu, untuk master-main nya 6.0.3 apakah ada link nya pak?
