### ISSUE TITLE
Request: Apabila PKL di lebih dari 1 tempat DUDI, maka tampilkan semua DUDI di table rapor

### ISSUE THREAD

**Issue by rendy43** [eraporsmk/erapor6#172]
Izin request pak, jika ada anak yg PKL di lebih dari 1 tempat mungkin bisa ditampilkan semua tempat PKL nya di table cetak rapor bukan hanya 1 tempat PKL saja, haturnuhun @masadi @eraporsmk 
![image](https://user-images.githubusercontent.com/119026620/211233573-037022f0-25bd-4d0c-b497-cfb6c6fc9f8b.png)

**Comment by asepcb100** [comment]
kan harusnya 1 siswa, 1 tempat IDUKA pa,
kalaupun 1 siswa ada 2 tempat iduka, pilih iduka yang siswanya dapat sertifikat PKLnya

**Comment by eraporsmk** [comment]
Sudah diakomodir di versi 6.0.5

**Comment by rendy43** [comment]
trm ksh admin,

krn PKL min 3 bulan sdgkn kadang2 tmpat PKL hnya mnrima 1 atau 2 bln shg tmbhnnya PKL d tmpt lain
