### ISSUE TITLE
 Illuminate\Database\QueryException

### ISSUE THREAD

**Issue by haqi89** [eraporsmk/erapor6#173]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: 
2. Versi Aplikasi: 
3. Versi Database:

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Database\QueryException

  could not find driver (SQL: select * from information_schema.tables where table_schema = public and table_name =sekolah and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

  1   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(App\Providers\AppServiceProvider))

      +2 vendor frames
  4   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(App\Providers\AppServiceProvider))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by ekaperintis** [comment]
aktifkan driver pgsql di php.ini, sepertinya itu driver posgress nya tidak ditemukan.

**Comment by imammh** [comment]
Sudah bisa,
Silahkan Update ke Versi 6.0.4 dengan CMD
Dilanjutkan dengan sinkron dengan CMD

Jika sudah terselesaikan, jangan lupa di **TUTUP** issue ini dengan **CLOSE**

**Comment by smakansa** [comment]
bagaiman cara menyelesaikan permasalahan tersebut, saya belum menemukan solusinya mohon dibantu. terimakasih.

versi erapor 6.04
