### ISSUE TITLE
kapan update erapor genap

### ISSUE THREAD

**Issue by Kunyank** [eraporsmk/erapor6#175]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai: erapor 6.0.3
1. Operating System: windows 10
2. Versi Aplikasi: 6.0.3
3. Versi Database:5.03
kapan rilis erapor untuk semester genap

**Comment by mashanif88** [comment]
iya dah pada nunggui buat raport PTS genap

**Comment by Kunyank** [comment]
iya itu apalagi sudah selesai UKK

**Comment by imammh** [comment]
Sudah bisa,
Silahkan Update ke Versi 6.0.4 dengan CMD
Dilanjutkan dengan sinkron dengan CMD

Jika sudah terselesaikan, jangan lupa di **TUTUP** issue ini dengan **CLOSE**
