### ISSUE TITLE
Tidak bisa registrasi erapor

### ISSUE THREAD

**Issue by Batara22** [eraporsmk/erapor6#176]
Registrasi Gagal. Server pusat tidak merespon 

![image](https://user-images.githubusercontent.com/127071702/223013948-10dce66d-3e79-45b7-a389-364d7e740b08.png)

**Comment by dendyms09** [comment]
update terlebih dahulu ke versi 6.0.3
namun untuk sekarang server pusat masih belum aktif untuk singkron erapor

**Comment by imammh** [comment]
Sudah bisa,
Silahkan Update ke Versi 6.0.4 dengan CMD

Jika sudah terselesaikan, jangan lupa di **TUTUP** issue ini dengan **CLOSE**
