### ISSUE TITLE
Tidak memiliki hak akses

### ISSUE THREAD

**Issue by ibrahimwahyus** [eraporsmk/erapor6#177]
![image](https://user-images.githubusercontent.com/67053543/226598293-b633fdf7-12e3-4a64-8fd5-1eb2ab989d70.png)

Versi 6.0.3

Mengapa tidak memiliki hak akses ya??
Tidak dapat sinkron dapodik jg?
Belum ada update kah? mau buat raport PAT Genap 2023 kelas 12

**Comment by imammh** [comment]
Sudah bisa,
Silahkan Update ke Versi 6.0.4 dengan CMD
Dilanjutkan dengan sinkron dengan CMD

Jika sudah terselesaikan, jangan lupa di **TUTUP** issue ini dengan **CLOSE**
