### ISSUE TITLE
Kenaikan atau Kelulusan

### ISSUE THREAD

**Issue by cdianym** [eraporsmk/erapor6#178]
belum ada menu kenaikan kelas atau kelulusan di semester genap

![image](https://user-images.githubusercontent.com/70784030/228140707-c93f9eb6-6d5f-452c-acc1-70fdebf70676.png)

![image](https://user-images.githubusercontent.com/70784030/228140856-20d94350-e090-48a8-a769-9cddefff109d.png)

**Comment by imammh** [comment]
Sudah bisa,
Silahkan Update ke Versi 6.0.4 dengan CMD
Dilanjutkan dengan sinkron dengan CMD

Jika sudah terselesaikan, jangan lupa di **TUTUP** issue ini dengan **CLOSE**

**Comment by cdianym** [comment]
Kenaikan kelas sudah tampil, tetapi kelas XII versi 5 kemarin tampilan di cetak Lulus.
Sedang yang di 6.0.4, kelas XII tetap tampil naik kelas

**Comment by cdianym** [comment]
![Uploading 16807607999528857878466651557086.jpg…]()

**Comment by indraksma** [comment]
Menu kenaikan kelas sudah ada di versi 6.0.4 cuma belum tersedia status kelulusan untuk kelas XII dan tidak ada pengecekan untuk sekolah yang masih memiliki rombel 4 tahun jika siswa masih kelas XII maka status kenaikan bukan status kelulusan seperti rombel yang 3 tahun. Solusinya saya tambah sendiri spt ini
![image](https://user-images.githubusercontent.com/45510960/230821518-9f6862b8-c6c6-4f37-8d72-548739b9b4af.png)
dan di component kenaikan kelas ditambah variabel baru untuk ambil data rombel 4 tahun ditampilkan ke view kenaikan-kelas-pd
