### ISSUE TITLE
Syncron Dapodik smester genap Berhasil tetapi datanya kosong

### ISSUE THREAD

**Issue by impeesa182** [eraporsmk/erapor6#179]
Operating System: windows 10 Ver.1909 Build 18363
Versi Aplikasi: 6.0.3
Versi Database:5.0.3

![image](https://user-images.githubusercontent.com/54379803/228387159-f313752f-703d-42de-a255-bda403ad5c09.png)

pada saat sync dapo smester genap tampil  pemberitahuan Sync Dapodik  berhasil tetapi datanya 0

**Comment by ariemusbandi** [comment]
belum ada solusinya ya?

**Comment by ibrahimwahyus** [comment]
![image](https://user-images.githubusercontent.com/67053543/229254794-cd175130-cc1a-4e2e-bcca-003c30f85f92.png)

Tempat kami malah tidak terhubung server dapodik, gimana yaa??

**Comment by imammh** [comment]
Masih dalam proses perbaikan di server pusat pak,

**Comment by imammh** [comment]
Sudah bisa,
Silahkan Update ke Versi 6.0.4 dengan CMD
Dilanjutkan dengan sinkron dengan CMD

Jika sudah terselesaikan, jangan lupa di **TUTUP** issue ini dengan **CLOSE**

**Comment by ariemusbandi** [comment]
> Sudah bisa, Silahkan Update ke Versi 6.0.4 dengan CMD Dilanjutkan dengan sinkron dengan CMD
> 
> Jika sudah terselesaikan, jangan lupa di **TUTUP** issue ini dengan **CLOSE**

Mohon maaf pak @imammh sinkron dengan CMD perintahnya apa?
