### ISSUE TITLE
Error saat setiap kali login, tapi akan normal ketika direfresh.

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#18]
Error saat login, tapi akan normal ketika direfresh.
![image](https://user-images.githubusercontent.com/49719997/203260702-5d9878a3-0099-44b5-8ae6-6737727da221.png)

**Comment by imammh** [comment]
sudah coba

git pull origin main

php artisan view:clear
php artisan config:cache
php artisan view:cache
php artisan route:cache

**Comment by ozonerik** [comment]
sudah, tetap

**Comment by ozonerik** [comment]
![image](https://user-images.githubusercontent.com/49719997/203433329-f16bc1ae-473f-42ab-aecf-040ce7946504.png)
