### ISSUE TITLE
Cetak PDF rapor

### ISSUE THREAD

**Issue by harsowidiantoB4** [eraporsmk/erapor6#180]
belum bisa cetak rapor untuk semester genap
untuk kelulusan dan kenaikan kelas

**Comment by ibrahimwahyus** [comment]
iyaa sama menunggu untuk rapor kelas 12 ini.. 
kapan server dapodik buka??

**Comment by imammh** [comment]
Segera mungkin, masih dalam proses terakhir perbaikan

Pada tanggal Sab, 1 Apr 2023 pukul 07.06 Ibrahim Wahyu Saputra <
***@***.***> menulis:

**Comment by imammh** [comment]
Sudah bisa,
Silahkan Update ke Versi 6.0.4 dengan CMD
Dilanjutkan dengan sinkron dengan CMD

Jika sudah terselesaikan, jangan lupa di **TUTUP** issue ini dengan **CLOSE**
