### ISSUE TITLE
Menu referensi data Guru/Tendik tidak lengkap

### ISSUE THREAD

**Issue by impeesa182** [eraporsmk/erapor6#182]
Operating System: windows 10 Ver.1909 Build 18363
Versi Aplikasi: 6.0.4
Versi Database:5.0.3

![image](https://user-images.githubusercontent.com/54379803/230104389-c46da25c-af6c-45c5-a3f3-dff1592d4239.png)

**Comment by eraporsmk** [comment]
Silahkan lakukan `git pull` ulang dan lakukan sync PTK lagi

Terima kasih
