### ISSUE TITLE
Cara sinkron wilayah?

### ISSUE THREAD

**Issue by ibrahimwahyus** [eraporsmk/erapor6#185]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: win 11
2. Versi Aplikasi: 6.0.4
3. Versi Database: 5.0.3

![image](https://user-images.githubusercontent.com/67053543/230212180-8a9b485e-1795-434f-b9ce-0a7f8b462688.png)

Tertulis sinkron melalui CMD caranya seperti apa ya?
Data wilayah itu isinya data apa soalnya kurang lengkap mau sinkronkan.

**Comment by impeesa182** [comment]
silahkan buka folder di C:\eRaporSMK\updater 
kemudian buka file "sinkron-dapodik"
terus masuka email yg sama dengan email dapodik
![image](https://user-images.githubusercontent.com/54379803/230214069-c85e2290-44d9-41ad-a9d5-9155683a050e.png)

kemidian pilih data yg mau di sync dengan cara memilih nomor yg ada

![image](https://user-images.githubusercontent.com/54379803/230214391-38c96adf-3c77-4353-a633-59aaa566303c.png)
 terus tekan enter

**Comment by ariemusbandi** [comment]
Sebaiknya di masukkan ke wiki nih, metode sinkron via php artisan
