### ISSUE TITLE
Assessment P5 

### ISSUE THREAD

**Issue by ariemusbandi** [eraporsmk/erapor6#186]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Ubuntu 20.04
2. Versi Aplikasi: 6.0.4
3. Versi Database: 5.0.3

Pada menu Pengaturan > Akses Pengguna tidak ada lagi fasilitas menambahkan hak akses Koordinator P5, 
Mohon penjelasannya bagaimana megisi nilai P5? @imammh 
![erapor604p5](https://user-images.githubusercontent.com/49692660/230212319-9c994a58-9cdb-4d02-a9b2-45312ccdb799.png)

**Comment by impeesa182** [comment]
bukannya Koordinator P5 ditambahkan dari dapodik? karena smester kemaren jg begitu

**Comment by ariemusbandi** [comment]
Udah coba entry perencanaan P5?

**Comment by impeesa182** [comment]
blum coba sih karena bukan  Koordinator P5

**Comment by ariemusbandi** [comment]
> blum coba sih karena bukan Koordinator P5

Apakah di tempat bapak sudah ada koordinator P5, jika sudah bisa bantu di coba untuk membuat perencanaan proyek nya
