### ISSUE TITLE
Menu kenaikan kelas XI pilihannya jadi lulus/tidak lulus setelah update

### ISSUE THREAD

**Issue by impeesa182** [eraporsmk/erapor6#187]
Operating System: windows 10 Ver.1909 Build 18363
Versi Aplikasi: 6.0.4
Versi Database:5.0.3

![image](https://user-images.githubusercontent.com/54379803/230227202-f447286b-66ef-43c6-abbd-317fe64d7158.png)

**Comment by ariemusbandi** [comment]
Saya juga mengalami hal yang sama

**Comment by impeesa182** [comment]
![image](https://user-images.githubusercontent.com/54379803/230236942-979b05de-f723-438a-90e1-b3b7f06f6d61.png)
kayaknya kebalik deh

**Comment by impeesa182** [comment]
saya coba ubah akhirnya bisa
![image](https://user-images.githubusercontent.com/54379803/230237176-863bcdf2-85e1-4439-91bf-e8b75594f0eb.png)

**Comment by ariemusbandi** [comment]
Di pull aja

**Comment by cdianym** [comment]
6.0.4,
Kenaikan kelas sudah bisa.
Cuma yang jadi masalah kelulusan kelas XII bunyinya juga kenaikan kelas.

Versi 5 terakhir kemarin sudah benar, tampilan menu memang kenaikan kelas, waktu diklik dan dilihat cetak rapor bunyinya lulus

**Comment by ariemusbandi** [comment]
Kita tunggu update selanjutnya, ini solusinya sudah di temukan bro @impeesa182 cuma kita nggak bisa pull request aja
