### ISSUE TITLE
TIDAK DAPAT MENAMBAHKAN PEKET UKK

### ISSUE THREAD

**Issue by Kunyank** [eraporsmk/erapor6#189]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: WIN 10
2. Versi Aplikasi: 6.0.4
3. Versi Database: 5.0.3
![image](https://user-images.githubusercontent.com/120827421/230281256-1d153cdc-9bfb-41b1-9813-87c55f47b348.png)

**Comment by ariemusbandi** [comment]
Sudah ditambahkan di referensi?
