### ISSUE TITLE
Sinkronisasi Wilayah, masih error

### ISSUE THREAD

**Issue by imammh** [eraporsmk/erapor6#19]
Saat melakukan sinkronisasi wilayah, muncul error seperti pada gambar berikut ini 
![gambar](https://user-images.githubusercontent.com/102570358/203288310-0d58cad0-fe76-4926-ba0a-32d9171be887.png)

**Comment by ozonerik** [comment]
sama setelah di update 
![image](https://user-images.githubusercontent.com/49719997/203321404-cefd605f-989e-44f1-b521-73800dcbb7ac.png)

**Comment by ozonerik** [comment]
sama setalah melakukan git pull origin main.
![image](https://user-images.githubusercontent.com/49719997/203321679-8b719dc8-a191-4d48-b25e-8211b09fc7b6.png)

**Comment by imammh** [comment]
![gambar](https://user-images.githubusercontent.com/102570358/203513771-46cf379d-e44a-4762-9ad9-4fd8fa7274b9.png)

Sama, lewat terminal juga error seperti ini...

**Comment by ozonerik** [comment]
> Saat melakukan sinkronisasi wilayah, muncul error seperti pada gambar berikut ini ![gambar](https://user-images.githubusercontent.com/102570358/203288310-0d58cad0-fe76-4926-ba0a-32d9171be887.png)

errors sudah solved belum pa?, di saya sudah solved setelah melakukan git pull origin main

**Comment by imammh** [comment]
> > Saat melakukan sinkronisasi wilayah, muncul error seperti pada gambar berikut ini ![gambar](https://user-images.githubusercontent.com/102570358/203288310-0d58cad0-fe76-4926-ba0a-32d9171be887.png)
> 
> errors sudah solved belum pa?, di saya sudah solved setelah melakukan git pull origin main , dilanjut php artisan erapor:update, php artisan sinkron:dapodik

Tetap belum terselesaikan masalah ini di saya
`git pull origin main`
`php artisan erapor:update`
`php artisan sinkron:dapodik`

Juga belum berhasil
![gambar](https://user-images.githubusercontent.com/102570358/203722414-f3890966-9c3a-4ddb-9d32-b0bf41db1dd6.png)

**Comment by eraporsmk** [comment]
Coba jalankan:

php artisan sinkron:erapor wilayah email_operator@gmail.com 1

**Comment by imammh** [comment]
Amaannnn.
Alhamdulillah
