### ISSUE TITLE
Perencanaan Nilai UKK

### ISSUE THREAD

**Issue by cdianym** [eraporsmk/erapor6#191]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: 
2. Versi Aplikasi: 
3. Versi Database:

Versi 6.0.4
Kaprogli tidak dapat membuat perencanaan penilaian UKK  karena pada saat memilih penguji internal tidak ada yang muncul.
Di versi 6.0.3 sudah sempat muncul hanya saja bermasalah di filter pemilihan penguji internal, 1 paket ujian hanya bisa 1 penguji internal

![Screenshot_20230407_144357_Chrome](https://user-images.githubusercontent.com/70784030/230566058-c19c88a6-3ebb-48ee-88e7-cc40ade67cf1.jpg)
![Screenshot_20230407_144241_Chrome](https://user-images.githubusercontent.com/70784030/230566071-b0fd1527-9f0a-46a9-9e33-bdcf38d3a524.jpg)

**Comment by masadi** [comment]
Coba update lagi dengan cara git pull
