### ISSUE TITLE
Eror pada saat daftar akun

### ISSUE THREAD

**Issue by kurikulum2591** [eraporsmk/erapor6#192]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: windows 10
2. Versi Aplikasi: 6.0
3. Versi Database:

![image](https://user-images.githubusercontent.com/130196318/230698175-49c5e7fd-a865-4a2d-8a63-047390f3dd17.png)

**Comment by kurikulum2591** [comment]
harus seperti apa ya?

**Comment by afdoal** [comment]
> harus seperti apa ya?

coba update dulu ke versi terbaru baru registrasi

**Comment by masadi** [comment]
Silahkan update ke versi 6.0.4 terlebih dahulu
