### ISSUE TITLE
dudi

### ISSUE THREAD

**Issue by patawari** [eraporsmk/erapor6#195]
data dudi tidak dapat masuk di erapor

**Comment by Kunyank** [comment]
data dudi tidak dapat di sinkron dari dapodik

**Comment by impeesa182** [comment]
cek dapodik
![image](https://user-images.githubusercontent.com/54379803/231620047-f4f50e88-0e67-4cc4-9e2c-c8a76e389a74.png)

**Comment by Kunyank** [comment]
sudah ada di dapodik tapi pada erapor tidak masuk

**Comment by smkronas** [comment]
https://github.com/eraporsmk/erapor6/issues/199
