### ISSUE TITLE
Update ke versi 6.0.4, tampilan data yang sudah diinput semester sebelumnya menjadi hilang

### ISSUE THREAD

**Issue by yayanch** [eraporsmk/erapor6#198]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Linux
2. Versi Aplikasi: 6.0.4
3. Versi Database: 5.0.3

Setelah update dari 6.0.3 ke 6.0.4 ada beberapa masalah yang muncul:
1. tampilan data nilai malah 0. pas di cek di database, nilainya sebetulnya ada. Hanya saja tidak tampil di aplikasi. 
2. Akses pengguna harus diatur ulang
3. dan beberapa permasalahan yang mengikutinya
Ada yang mengalami hal serupa ? Mohon bantuannnya..terima kasih.

![WhatsApp Image 2023-04-17 at 07 40 00](https://user-images.githubusercontent.com/62583586/232502761-0170ae41-7957-4a6b-8f6f-1fbcb4427953.jpeg)

**Comment by cahyadiwily** [comment]
karena ganti semester maka selain data pokok akan kosong, perlu dilakukan sinkronisasi lagi

**Comment by yayanch** [comment]
betul..saya salah pilih semester..pada semester sebelumnya, datanya masih utuh..makasih informasinya..
