### ISSUE TITLE
menambah DU/DI tidak bisa sinkron 

### ISSUE THREAD

**Issue by smkronas** [eraporsmk/erapor6#199]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System:  Windows
2. Versi Aplikasi: 6.0.4
3. Versi Database: 5.0.3

Pada dapodik sudah di inputkan
![image](https://user-images.githubusercontent.com/118788751/234425481-24513312-8ccf-465e-8663-70ac893e8ba3.png)

pada erapor
![image](https://user-images.githubusercontent.com/118788751/234425645-da978d6f-d972-49be-8726-d4468cb39df3.png)

padahal sudah sering sinkronisasi

**Comment by jonikonye** [comment]
coba di klik menu Prakerin/teaching nya... tambahkan nama dan pembimbin

**Comment by smkronas** [comment]
terima kasih, sudah berhasil masuk.
