### ISSUE TITLE
Versi App & Database tidak muncul di Linux

### ISSUE THREAD

**Issue by hid0** [eraporsmk/erapor6#2]
pada OS Linux nama aplikasi muncul dapat dari file .env
![image](https://user-images.githubusercontent.com/20245892/202661747-57b799b7-c406-46a2-9cc9-394c1f3e49cf.png)
akan tetapi untuk versi app dan db ndak muncul
![image](https://user-images.githubusercontent.com/20245892/202662224-5faa8c76-2fc5-43e1-953c-2b7111cfe018.png)

dan saya cek menggunakan artisan tinker ternyata hasilnya null
![image](https://user-images.githubusercontent.com/20245892/202662007-001e930f-fce7-4d15-a395-96af3e7bddf0.png)

**Comment by eraporsmk** [comment]
Silahkan jalankan:
php artisan erapor:update

**Comment by hid0** [comment]
:) oke berhasil, terimakasihi
