### ISSUE TITLE
sinkronisasi dengan erapor synchronizer apakah masih bisa dilakukan ? apakah masih support untuk erapor versi 6 ini?

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#20]
erapor yang disimpan di vps, tidak bisa realtime terupdate datanya, walaupun data didapodik sudah disinkronkan. 
jika menggunakan erapor synchronizer seperti versi dulu, enak bisa realtime push data ke erapor.

**Comment by eraporsmk** [comment]
Synchronizer sudah tidak dipakai di versi 6 bapak.
Untuk data dapodik yang telah di sinkron, akan di update dalam 1x24 jam

Terima kasih
