### ISSUE TITLE
Menu Larporan pada akun walas tidak muncul/tampil di erapor 6.0.4

### ISSUE THREAD

**Issue by smknduatebo** [eraporsmk/erapor6#200]
hilangnya menu laporan untuk walas sehingga untuk mencetak rapor tidak bisa

![Screenshot_2](https://user-images.githubusercontent.com/132114235/235277279-112640ab-1904-49b1-9af4-294e0e2a3274.png)

**Comment by masadi** [comment]
Menu di aplikasi eraporsmk berbasis hak akses, pastikan guru tsb sudah memiliki hak akses wali kelas.
Hak akses tampil di bawah Nama Guru dibagian pojok kanan atas
