### ISSUE TITLE
TABEL WALAS WALI KELAS DI DIBERANDA AKUN WALAS TIDAK MUNCUL (ERAPOR V6.04)

### ISSUE THREAD

**Issue by trsetyo** [eraporsmk/erapor6#201]
**TABEL WALAS WALI KELAS DI DIBERANDA AKUN WALAS TIDAK MUNCUL (ERAPOR V6.04)**

1. Operating System: Windows 10 Enterprise 64-bit (10.0, Build 10240) (10240.th1.150709-1700)
2. Versi Aplikasi: 6.0.4
3. Versi Database: 5.0.3

Mohon bantuan kendala berikut yang berhubungan dengan Wali Kelas:
A. Tabel Walas Wali Kelas Di Beranda Akun Wali Kelas **Tidak Muncul**.
![lp3](https://user-images.githubusercontent.com/132535675/236111124-33c6ff78-1841-4150-91b0-b2dcc5b709d1.png)

B. Pada Sidebar, Menu "Wali Kelas" **Tidak Muncul**.
![LP4](https://user-images.githubusercontent.com/132535675/236111148-485ccbbb-ba64-4159-b66f-f3d28a7cad8d.png)

C. Login Akun Admin, 
>> pada menu "Pengaturan>Akses Pengguna", pada kolom "Jenis Pengguna" Status "Wali Kelas" **Tidak Muncul**
![lp2](https://user-images.githubusercontent.com/132535675/236110950-51501d3f-f27b-4266-9848-4d66169bb527.png)
>> sedangkan pada menu "Rombongan Belajar>Reguler" ybs sudah terdata sebagai "Wali Kelas"
![Lp 1](https://user-images.githubusercontent.com/132535675/236111065-6898ca93-1fb5-4338-b7c1-9a366cdb814f.png)

**Comment by xeizer** [comment]
Coba sebagai Administrator, lakukan Atur Ulang Pengguna
Pengaturan-> Akses Pengguna ->Atur Ulang Pengguna
