### ISSUE TITLE
Setelah update ke versi 6.0.4 tidak bisa login, pesan erornya email tidak terdaftar. Saya menggunakan hosting.

### ISSUE THREAD

**Issue by Rizki-1144089** [eraporsmk/erapor6#202]
![Capture](https://user-images.githubusercontent.com/18274177/236359566-32ff6b28-bdea-4c90-a5b0-e62e918ae9f8.PNG)

**Comment by ibrahimwahyus** [comment]
Bisa di hostingkan ya?? Gimana caranya adakah tutorialnya??

**Comment by Rizki-1144089** [comment]
Bisa dihostingkan, kalau mau lebih simpel hubungi saja jasa IT untuk menghostingkan erapor
