### ISSUE TITLE
Menu Hapus User agar role user yg baru berubah

### ISSUE THREAD

**Issue by c0mbra1n** [eraporsmk/erapor6#203]
mohon kepada dev dengan sangat hormat, munculkan lagi menu hapus user agar bisa di generate ulang user si usert tersebut role nya berubah

jadi gini, dulu misal ada user wali kelas, kemudian wali kelas nya ganti jadi user lain.
kalo dulu itu wali kelas yg baru di hapus dulu kemudian di generate lagi sehingga walas yg baru sudah bisa akses walas.
sekarang di dapodik guru tersebut sudah di ubah jadi walas, sudah sinkron beberapa kali tapi ga berubah2 status walas nya di erapor .
sudah coba di generate beberapa kali tetap ga berubah, harus di hapus dulu user nya kayak dulu, masalhnya sekarang tombol delete nya gak ada. moho bantuanya karena peran walas itu penting dan tercantum di hasil print rapor

**Comment by restupamuji** [comment]
Masuk akun admin pak.

![image](https://github.com/eraporsmk/erapor6/assets/73053059/4675ac45-5c42-4c99-85df-bb8b226a233a)

Di Menu Pengaturan - Akses Pengguna. Dipojok kanan atas ada tombol Atur Ulang Pengguna.

**Comment by c0mbra1n** [comment]
sudah pa, itu sudah dilakukan, tapi tetap wali kelas yang dulu masih nempel di rombel nya, sedangkan di dapodik sudah wali kelas yg baru. kira2 apakah ada masalah dimananya itu? kalo dulu ada menu hapus pengguna itu , walas yg lama di hapus dulu, nanti pas di atur ulang pengguna bakal muncul lagi tuh si walas lama tapi sudah ga jadi walas di akun nya.
jadi mohon pertimbangkan munculkan kembali tombol hapus agar mengatasi masalah ini,

**Comment by asepcb100** [comment]
sinkron ulang dapodik, kemudian, tunggu 1x24 jam, lalu sinkron kembali erapornya

**Comment by eraporsmk** [comment]
Jika melakukan perubahan wali kelas di dapodik, setelah dapodiknya di sinkron tunggu 1x24 jam.
Kemudian di eRapor silahkan sinkron Rombongan Belajar nya saja.
Setelah itu silahkan atur ulang pengguna
