### ISSUE TITLE
BUG Buat K13

### ISSUE THREAD

**Issue by dian21guns** [eraporsmk/erapor6#204]
**Sekolah Belum Menggunkan Kurukulum Merdeka, Bagau Mana Saya Iput Nilai Buat K13 Sementara Data isian Nya Masih Kosong.**
Aplikasi yang sedang dipakai:
1. Operating System: Windows 10
2. Versi Aplikasi:  6.04
3. Versi Database:

**Comment by imammh** [comment]
Silahkan ikuti pedoman dan petunjuk penilaian K13 berikut ini [https://drive.google.com/file/d/19tP2LIclhq0a5phMsBnlVQuzdZynPeRV/view?usp=share_link](https://drive.google.com/file/d/19tP2LIclhq0a5phMsBnlVQuzdZynPeRV/view?usp=share_link)
