### ISSUE TITLE
Setelah update ke 6.0.4 data ekskul hilang

### ISSUE THREAD

**Issue by RahmanChastury** [eraporsmk/erapor6#205]
Setelah update ke 6.0.4 data ekstrakulikuler dan anggota ekstrakurikuler hilang, mohon solusinya

![New Picture](https://github.com/eraporsmk/erapor6/assets/135337188/691e9e3b-c84b-40c8-ba7a-e2560e274ae9)

**Comment by ibrahimwahyus** [comment]
Sama, minimal harusnya ekskul untuk satu tahun yaa bukan tiap satu semester input lagi..
Coba ada fitur tarik data ekskul semester sebelumnya..

**Comment by RahmanChastury** [comment]
Iya betul Pak Ibrahim, sy sudah dapat solusinya Pak. Cek didapodik pada menu --> Sekolah -->Ekstrakurikuler di menu ini diinput ekstrakurikuler lagi. Semoga dapat membantu.

**Comment by ibrahimwahyus** [comment]
iyaa pak jadi harus input lagi.. coba ada fitur tarik data semester lalu

**Comment by eraporsmk** [comment]
@ibrahimwahyus Karena eRapor bersumber dari dapodik, dan di dapodik sendiri juga input ekskul tiap semester.
Semoga ke depan dapodik input ekskul hanya setahun sekali :)
