### ISSUE TITLE
Data Ganda cetak rapot ekskul

### ISSUE THREAD

**Issue by resqy67** [eraporsmk/erapor6#209]
![16865413367055527052122062306313](https://github.com/eraporsmk/erapor6/assets/62694501/5110a8c6-20bf-4f2c-acb2-9a0fca1f1a56)
ekstrakurikuler cetak rapot data ganda dengan deskripsi berbeda dengan kegiatan ekstrakurikuler. mohon bantuannya, bagaimana mengatasinya?...
Aplikasi yang sedang dipakai:
1. Operating System: win 11
2. Versi Aplikasi: 6.0.4
3. Versi Database: 5.0.3

**Comment by masadi** [comment]
Sudah diperbaiki di versi 6.0.5, silahkan update
