### ISSUE TITLE
Apakah Akses Pengguna tidak bisa dihapus ? 

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#21]
Tombol Hapus Pengguna sudah tidak ada ? apakah memang tidak ada fasilitas hapus akses pengguna ?
![image](https://user-images.githubusercontent.com/49719997/203320020-555170cd-2513-479c-abaf-937045d9f900.png)

**Comment by eraporsmk** [comment]
Hapus pengguna sudah ditiadakan bapak

Terima kasih
