### ISSUE TITLE
Error Singkron Data DU/DI

### ISSUE THREAD

**Issue by fhiethan** [eraporsmk/erapor6#211]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Win 10
2. Versi Aplikasi:  6.0.4
3. Versi Database: 5.0.3

![image](https://github.com/eraporsmk/erapor6/assets/107638516/2152c4d6-8b92-4499-9b03-70c5c9498261)

bagaimana mengatasi error seperti diatas?

**Comment by asepcb100** [comment]
git origin ulang saja pa, terus coba sinkron ulang

**Comment by fhiethan** [comment]
sudah, tetap hasilnya seperti itu pak

**Comment by masadi** [comment]
Pastikan sudah memakai versi 6.0.5
