### ISSUE TITLE
Data DuDi untuk Penilaian Prarkerin Tidak Muncul

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#22]
Data DuDi untuk Penilaian Prarkerin Tidak Muncul
![image](https://user-images.githubusercontent.com/49719997/203322501-6e4a0fbf-5716-4446-954e-31dcad6f9b2e.png)
padahal didapodik sudah didata dan disinkron
![image](https://user-images.githubusercontent.com/49719997/203322608-18f09865-0fbe-41f7-9d1f-4c0e0bbcca66.png)

**Comment by ozonerik** [comment]
padahal data dudi sudah tersinkron
![image](https://user-images.githubusercontent.com/49719997/203645328-6116a386-e1d4-4c06-9b83-d2b410664db6.png)

**Comment by ozonerik** [comment]
referensi di dudi juga sudah masuk
[image](https://user-images.githubusercontent.com/49719997/204058223-d73c0075-efd2-443d-9c93-dcbf54ff1d25.png)

**Comment by eraporsmk** [comment]
Di dapodik, pastikan sudah melakukan ini:

1. Di menu Sekolah, tab Relasi Dunia Usaha & Industri, sudah ditambah data DUDI
2. di menu Sekolah, tab Perjanjian Kerja Sama (PKS), pastikan sudah ditambah MoU
3. Klik di data MoU yang sudah ditambah, kemudian klik tombol Prakerin/Teaching Factory
4. Di pop up Prakerin/Teaching Faktor, silahkan tambah Aktifitas PD
5. Klik Aktifitas PD yang sudah ditambah, kemudian klik tombol:
- Anggota, tambahkan PD yang mengikuti Prakerin
- Pembimbing, Tambahkan Guru yang menjadi pembimbing prakerin
