### ISSUE TITLE
NA (Nilai Akhir) pada catatan akademik, sepertinya salah formulasi.

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#24]
Na pada catatan akademik, sepertinya salah formulasi.
![image](https://user-images.githubusercontent.com/49719997/203432180-adb56106-f930-412a-9840-3c7b44b801e2.png)

**Comment by eraporsmk** [comment]
Silahkan git pull lagi kemudian Generate ulang Nilainya di laman Beranda

Terima Kasih
