### ISSUE TITLE
Usulan Deskripsi Cetak erapor untuk Capaian Kompetensi bila kosong

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#25]
Usulan Deskripsi Cetak erapor untuk Capaian Kompetensi bila kosong, bisa dibuat otomatis
![nilai akhir](https://user-images.githubusercontent.com/49719997/203450288-b70527f2-5570-497b-b8bd-c1959ed2c76c.jpg)
![capaian kompetensi](https://user-images.githubusercontent.com/49719997/203450308-89dbcd1f-ab5b-42b7-a8fe-455fbce3edfd.jpg)
![deskripsi capaian kompetensi](https://user-images.githubusercontent.com/49719997/203450318-046d42a9-e472-4da4-84ff-9c863ad21f6a.jpg)

**Comment by ariemusbandi** [comment]
di pengaturan pembelajaran kelompok mapel nya muncul nggak? saya nggak muncul, jadinya mapel merdeka nggak ada di akun guru

**Comment by ozonerik** [comment]
> di pengaturan pembelajaran kelompok mapel nya muncul nggak? saya nggak muncul, jadinya mapel merdeka nggak ada di akun guru

di saya, kelompok mapelnya muncul

**Comment by eraporsmk** [comment]
> Usulan Deskripsi Cetak erapor untuk Capaian Kompetensi bila kosong, bisa dibuat otomatis ![nilai akhir](https://user-images.githubusercontent.com/49719997/203450288-b70527f2-5570-497b-b8bd-c1959ed2c76c.jpg) ![capaian kompetensi](https://user-images.githubusercontent.com/49719997/203450308-89dbcd1f-ab5b-42b7-a8fe-455fbce3edfd.jpg) ![deskripsi capaian kompetensi](https://user-images.githubusercontent.com/49719997/203450318-046d42a9-e472-4da4-84ff-9c863ad21f6a.jpg)

Otomatis ambil dari mana pak jika kosong?
Deskripsi default gitu ya?

Terima Kasih

**Comment by ozonerik** [comment]
> > Usulan Deskripsi Cetak erapor untuk Capaian Kompetensi bila kosong, bisa dibuat otomatis ![nilai akhir](https://user-images.githubusercontent.com/49719997/203450288-b70527f2-5570-497b-b8bd-c1959ed2c76c.jpg) ![capaian kompetensi](https://user-images.githubusercontent.com/49719997/203450308-89dbcd1f-ab5b-42b7-a8fe-455fbce3edfd.jpg) ![deskripsi capaian kompetensi](https://user-images.githubusercontent.com/49719997/203450318-046d42a9-e472-4da4-84ff-9c863ad21f6a.jpg)
> 
> Otomatis ambil dari mana pak jika kosong? Deskripsi default gitu ya?
> 
> Terima Kasih

misalkan saja, otomatis tertulis: menunjukan penguasaan yang baik dalam semua aktivitas, dan tidak perlu ada yang ditingkatkan.  jika tujuan pembelajaran tercapai semua.

**Comment by eraporsmk** [comment]
> 

Baik pak, terima kasih atas usulannya
