### ISSUE TITLE
Registrasi Gagal .

### ISSUE THREAD

**Issue by Didik-Suryanto** [eraporsmk/erapor6#28]
saya sudah berhasil install, tapi selalu gagal saat register dan muncul pesan "Password Salah",
kalau Database dan Dataweb saya copy dari hasil backup, bisa normal tapi kembali ke versi 5.1.6 ...

**Comment by imammh** [comment]
Coba gunakan pasword dapodik lama
Jika mau registrasi

Jika Migrasi dari 5.xx ke 6.xx
Mestinya tidak perlu registrasi ulang

**Comment by eraporsmk** [comment]
@Didik-Suryanto 
Untuk merubah versi aplikasi dari 5.1.6 ke 6.0.0, silahkan buka file (double click) C:\eRaporSMK\updater\update-erapor.bat

Terima Kasih

**Comment by Didik-Suryanto** [comment]
inggih ...

terima kasih ...

**Comment by fathuralfian** [comment]
kalo ga bisa regis/login solusinya gimana?

**Comment by Didik-Suryanto** [comment]
masih belum bisa, pak ...
register pakai e-mail dapodik yang lama juga belum bisa ...
