### ISSUE TITLE
Menu Aksi Hapus Pengguna Tidak Muncul

### ISSUE THREAD

**Issue by FirinAhmad** [eraporsmk/erapor6#29]
![aksespengguna](https://user-images.githubusercontent.com/118964602/203724626-7df0aece-0337-4b6c-91ac-dec06e2214fd.PNG)
ketika menggunakan fresh install menu Aksi hapus pengguna muncul namun tidak bisa dieksekusi. Setelah dicoba update, Menu Aksi Hapus pengguna tidak muncul. Mohon bantuannya

**Comment by eraporsmk** [comment]
Tombol hapus pengguna sudah dihilangkan.
Terima kasih
