### ISSUE TITLE
Sinkronisasi berhasil semua, tapi data tetap masih kurang

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#3]
Sinkronisasi berhasil semua, tapi data tetap masih kurang,
pada item: mata pelajaran kurikulum, wilayah
![sinkronisasi berhasil tapi masih kurang](https://user-images.githubusercontent.com/49719997/202731419-6a42d073-88a9-477f-bb4f-10932ca06f96.jpg)

**Comment by vinaoo** [comment]
idem,

warning saat sync

Mapel Kurikulum
cURL error 56: 
Recv failure: 
Connection was reset 
(see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://103.40.55.242/erapor_server/api/mata_pelajaran_kurikulum/3000
C:\eRaporSMK\dataweb\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:211


Wilayah
BadMethodCallException
Call to undefined method App\Models\Mst_wilayah::withTrashed()
http://localhost:8154/sinkronisasi/dapodik

Illuminate\Database\Eloquent\Model::throwBadMethodCallException
C:\eRaporSMK\dataweb\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:71

Solusinya bagaimana ya? tks

**Comment by ozonerik** [comment]
sepertinya ada extensi yg dari phpnya belum di enable kan

**Comment by ozonerik** [comment]
sudo apt install php7.4-bcmath
sudo apt install php8.0-bcmath
sudo phpenmod bcmath
sudo apt install php7.4-mbstring
sudo apt install php8.0-mbstring
sudo phpenmod mbstring
sudo apt install php7.4-xml
sudo apt install php8.0-xml
sudo phpenmod xml
sudo apt install php7.4-gd
sudo apt install php8.0-gd
sudo phpenmod gd
sudo apt install php7.4-curl
sudo apt install php8.0-curl
sudo phpenmod curl
sudo apt install php7.4-zip
sudo apt install php8.0-zip
sudo phpenmod zip
sudo service apache2 restart
