### ISSUE TITLE
Beda Jumlah GTK dan Peserta didik antara Dapodik dan Erapor

### ISSUE THREAD

**Issue by FirinAhmad** [eraporsmk/erapor6#30]
![beranda erapor](https://user-images.githubusercontent.com/118964602/203824844-02d1e8f9-f15b-4010-9535-6e8fa4c15512.png)
![sinkronisasi_erapor](https://user-images.githubusercontent.com/118964602/203824853-485d1de8-4d31-44fc-a591-a11465c47585.png)
Beda Jumlah GTK dan Peserta Didik antara Dapodik dan Erapor. GTK dan Peserta didik sudah dimutasi dari Dapodik , sudah sinkronisasi dapodik & erapor (sudah lebih dari 1x24 jam) namun data PD & GTK tsb masih ada di erapor, sedang menu hapus pengguna sudah ditiadakan.

**Comment by imammh** [comment]
Pengalaman kami dari versi-versi sebelumnya, 
Saat nanti mapping pembelajaran, 
anak tersebut bisa dikeluarkan dari rombelnya, 
![gambar](https://user-images.githubusercontent.com/102570358/203828160-ee9c634a-57f7-4d58-a999-3927778850ce.png)

sehingga tidak akan muncul lagi di daftar siswa anggota rombel tersebut, ketika melakukan pengisian nilai.

**Comment by eraporsmk** [comment]
> ![beranda erapor](https://user-images.githubusercontent.com/118964602/203824844-02d1e8f9-f15b-4010-9535-6e8fa4c15512.png) ![sinkronisasi_erapor](https://user-images.githubusercontent.com/118964602/203824853-485d1de8-4d31-44fc-a591-a11465c47585.png) Beda Jumlah GTK dan Peserta Didik antara Dapodik dan Erapor. GTK dan Peserta didik sudah dimutasi dari Dapodik , sudah sinkronisasi dapodik & erapor (sudah lebih dari 1x24 jam) namun data PD & GTK tsb masih ada di erapor, sedang menu hapus pengguna sudah ditiadakan.

Silahkan update kembali aplikasi erapornya

Terima kasih

**Comment by eraporsmk** [comment]
> Pengalaman kami dari versi-versi sebelumnya, Saat nanti mapping pembelajaran, anak tersebut bisa dikeluarkan dari rombelnya, ![gambar](https://user-images.githubusercontent.com/102570358/203828160-ee9c634a-57f7-4d58-a999-3927778850ce.png)
> 
> sehingga tidak akan muncul lagi di daftar siswa anggota rombel tersebut, ketika melakukan pengisian nilai.

Saat mapping pembelajaran, ada anggota rombel yang dikeluarkan otomatis atau seperti apa pak?

**Comment by FirinAhmad** [comment]
> Pengalaman kami dari versi-versi sebelumnya, Saat nanti mapping pembelajaran, anak tersebut bisa dikeluarkan dari rombelnya, ![gambar](https://user-images.githubusercontent.com/102570358/203828160-ee9c634a-57f7-4d58-a999-3927778850ce.png)
> 
> sehingga tidak akan muncul lagi di daftar siswa anggota rombel tersebut, ketika melakukan pengisian nilai.

Terima kasih informasinya bapak. sangat membantu.

**Comment by FirinAhmad** [comment]
> > ![beranda erapor](https://user-images.githubusercontent.com/118964602/203824844-02d1e8f9-f15b-4010-9535-6e8fa4c15512.png) ![sinkronisasi_erapor](https://user-images.githubusercontent.com/118964602/203824853-485d1de8-4d31-44fc-a591-a11465c47585.png) Beda Jumlah GTK dan Peserta Didik antara Dapodik dan Erapor. GTK dan Peserta didik sudah dimutasi dari Dapodik , sudah sinkronisasi dapodik & erapor (sudah lebih dari 1x24 jam) namun data PD & GTK tsb masih ada di erapor, sedang menu hapus pengguna sudah ditiadakan.
> 
> Silahkan update kembali aplikasi erapornya
> 
> Terima kasih

Sudah diupdate dan sudah sesuai angkanya pak. Terima kasih. Masih ada kendala PTK yg sebelumnya sudah ada di erapor ketika PTK tersebut dimutasi dr dapodik datanya masih tetap ada di erapor. Terima kasih.

**Comment by imammh** [comment]
> > > ![beranda erapor](https://user-images.githubusercontent.com/118964602/203824844-02d1e8f9-f15b-4010-9535-6e8fa4c15512.png) ![sinkronisasi_erapor](https://user-images.githubusercontent.com/118964602/203824853-485d1de8-4d31-44fc-a591-a11465c47585.png) Beda Jumlah GTK dan Peserta Didik antara Dapodik dan Erapor. GTK dan Peserta didik sudah dimutasi dari Dapodik , sudah sinkronisasi dapodik & erapor (sudah lebih dari 1x24 jam) namun data PD & GTK tsb masih ada di erapor, sedang menu hapus pengguna sudah ditiadakan.
> > 
> > 
> > Silahkan update kembali aplikasi erapornya
> > Terima kasih
> 
> Sudah diupdate dan sudah sesuai angkanya pak. Terima kasih. Masih ada kendala PTK yg sebelumnya sudah ada di erapor ketika PTK tersebut dimutasi dr dapodik datanya masih tetap ada di erapor. Terima kasih.

Jika masalah utama sudah teratasi, silahkan di close dulu pak.

**Comment by FirinAhmad** [comment]
baik pak. Terima kasih. sangat membantu.
