### ISSUE TITLE
Penilaian untuk PKL Kelas XI di Kurikulum 2013 tidak bisa diakses

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#32]
Penilaian untuk PKL Kelas XI di Kurikulum 2013 tidak bisa diakses
![image](https://user-images.githubusercontent.com/49719997/203870812-d1e400ce-1c02-499f-b685-22d59093c636.png)

**Comment by imammh** [comment]
@ozonerik ini posisi siswanya sekarang kelas berapa pak ?

**Comment by ozonerik** [comment]
kelas xi

**Comment by ozonerik** [comment]
karena utk yg kelas xi, masing menggunakan K13, dan kebetulan PKL nya di kelas Xi

**Comment by ozonerik** [comment]
solved
