### ISSUE TITLE
Reset Hak Akses pengguna tidak bisa

### ISSUE THREAD

**Issue by WARDI-NURYANTO** [eraporsmk/erapor6#33]
![image](https://user-images.githubusercontent.com/119034175/203921375-a3918c47-15e0-4898-9286-a2234cdb137f.png)

MOHON SOLUSINYA ?

**Comment by imammh** [comment]
Mungkin  bisa diberikan penjelasan, kronologinya seperti apa pak.

**Comment by eraporsmk** [comment]
Masalahnya kenapa?
Bingung juga mau ngasih solusi... :)

Terima kasih

**Comment by ozonerik** [comment]
> Masalahnya kenapa?
> Bingung juga mau ngasih solusi... :)
> 
> Terima kasih

mungkin PTK yg bersangkutan sudah tidak nenjabat koord p5 lg.

**Comment by hilmah1** [comment]
Maksudnya itu tidak bisa hapus akun pengguna, untuk kemudian di atur ulang pengguna. Karena guru yang seharusnya tidak menjabat menjadi 

> Masalahnya kenapa? Bingung juga mau ngasih solusi... :)
> 
> Terima kasih

Maksudnya kenapa tombol hapus akun pengguna tidak ada, karena guru yang bersangkutan itu sebenarnya bukan koordinator P5, tetapi setelah sinkron malah dapat akun koordinator P5. Ketika instaler erapor pertama direlease yang ukuran masih 380 an MB tombol tersebut masih ada, tetapi ketika diupdate erapor nya atau menggunakan instaler ke dua yang berukuran sekitar 400 MB, tombol hapus akun hilang berganti jadi detail saja. Maaf sebenarnya bukan post saya :), tapi hal tersebut juga terjadi di erapor saya.

**Comment by hilmah1** [comment]
> Masalahnya kenapa? Bingung juga mau ngasih solusi... :)
> 
> Terima kasih

Maksudnya kenapa tombol hapus akun pengguna tidak ada, karena guru yang bersangkutan itu sebenarnya bukan koordinator P5, tetapi setelah sinkron malah dapat akun koordinator P5. Ketika instaler erapor pertama direlease yang ukuran masih 380 an MB tombol tersebut masih ada, tetapi ketika diupdate erapor nya atau menggunakan instaler ke dua yang berukuran sekitar 400 MB, tombol hapus akun hilang berganti jadi detail saja. Maaf sebenarnya bukan post saya :), tapi hal tersebut juga terjadi di erapor saya.

**Comment by hilmah1** [comment]
> Masalahnya kenapa? Bingung juga mau ngasih solusi... :)
> 
> Terima kasih

Maksudnya @eraporsmk @masadi , kenapa tombol hapus akun pengguna tidak ada, karena guru yang bersangkutan itu sebenarnya bukan koordinator P5, tetapi setelah sinkron malah dapat akun koordinator P5. Ketika instaler erapor pertama direlease yang ukuran masih 380 an MB tombol tersebut masih ada, tetapi ketika diupdate erapor nya atau menggunakan instaler ke dua yang berukuran sekitar 400 MB, tombol hapus akun hilang berganti jadi detail saja. Maaf sebenarnya bukan post saya :), tapi hal tersebut juga terjadi di erapor saya.

**Comment by WARDI-NURYANTO** [comment]
> 

iya betul seperti itu kasusnya
