### ISSUE TITLE
Bagaimana Cara Melakukan Penilaian Prakerin di Erapor versi terbaru ini ?

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#35]
Bagaimana Cara Melakukan Penilaian Prakerin di Erapor versi terbaru ini ? @eraporsmk @masadi 
#22

**Comment by eraporsmk** [comment]
Di dapodik, pastikan sudah melakukan ini:
1. Di menu Sekolah, tab Relasi Dunia Usaha & Industri, sudah ditambah data DUDI 
2. di menu Sekolah, tab Perjanjian Kerja Sama (PKS), pastikan sudah ditambah MoU 
3. Klik di data MoU yang sudah ditambah, kemudian klik tombol Prakerin/Teaching Factory
4. Di pop up Prakerin/Teaching Faktor, silahkan tambah Aktifitas PD
5. Klik Aktifitas PD yang sudah ditambah, kemudian klik tombol:
- Anggota, tambahkan PD yang mengikuti Prakerin
- Pembimbing, Tambahkan Guru yang menjadi pembimbing prakerin

**Comment by ozonerik** [comment]
yg menilai pkl adalah hak akses pembimbing, atau wali kelas? atau operator dapodik?

**Comment by eraporsmk** [comment]
Guru yang memilik hak akses Penguji Internal UKK, dan yang dipilih sebagai penguji internal oleh kepala program saat melakukan perencaan penilaian UKK

**Comment by imammh** [comment]
> Guru yang memilik hak akses Penguji Internal UKK, dan yang dipilih sebagai penguji internal oleh kepala program saat melakukan perencaan penilaian UKK

Sepertinya kurang solusi ini kurang tepat dengan pertanyaannya

**Comment by ozonerik** [comment]
maaf, yang saya maksud

> Guru yang memilik hak akses Penguji Internal UKK, dan yang dipilih sebagai penguji internal oleh kepala program saat melakukan perencaan penilaian UKK

maaf, yang saya maksud, penilaian Prakerin / PKL, siapa yang akan menilai ? jika di versi 5.1.6 kan yang diberikan hak akses adalah wali kelas, untuk yang erapor terbaru ini siapa ?
