### ISSUE TITLE
Akses tidak sah! pada saat ingin mendownload template Tujuan Pembelajaran

### ISSUE THREAD

**Issue by hid0** [eraporsmk/erapor6#51]
![image](https://user-images.githubusercontent.com/20245892/204947013-63f6e153-11ba-4079-abd7-f742e10293f7.png)
:) mohon segera disolve

**Comment by ibrahimwahyus** [comment]
gimana gan cara upload eraport SMK ini ke hosting website sekolah? adakah tutorialnya?

**Comment by hid0** [comment]
> gimana gan cara upload eraport SMK ini ke hosting website sekolah? adakah tutorialnya?

🙏🏻blm buat tutorial

**Comment by hid0** [comment]
👍🏻solved in recent [commit](https://github.com/eraporsmk/erapor6/releases/tag/v6.0.1)
