### ISSUE TITLE
Server Error 500 pada saat Simpan Nilai Akhir

### ISSUE THREAD

**Issue by herismk** [eraporsmk/erapor6#55]
Mau simpan nilai akhir muncul kode error 500.
![Uploading 16699956609816029804291310520031.jpg…]()

**Comment by herismk** [comment]
Awalnya tidak bisa di simpan nilai akhir, tp pada saat mengganti referensi tujuan pembelajaran, dan isi nilai akhir lagi, pas mau di simpan jadi error 500

**Comment by mrsutarna** [comment]
Sama pak, saya juga. gara gara hapus Tujuan Pembelajaran lalu buat lagi tujuan yang baru ketika input nilai akhir lagi malah error 500.

**Comment by herismk** [comment]
Haduhh.., tadi itu lagi belajar otak atik, biar besok klo di tanya guru
bisa jawab, malah error. Nanti kabari klo udah dapet solusinya.

Pada tanggal Jum, 2 Des 2022 23.13, mrsutarna ***@***.***>
menulis:

**Comment by mrsutarna** [comment]
Sementara belum ada solusi Pak, kalau bener2 terpaksa install ulang. tentunya harus mapping ulang.

**Comment by herismk** [comment]
Waktunya udah mepet, takutnya gak keburu. Mudah2an besok ada solusi. Klo bener2 install ulang, abis maping langsung di backup

**Comment by herismk** [comment]
Alhamdulillah..., done
