### ISSUE TITLE
[eRaporSMK v6.0.1] Bug Hasil Cetak Rapor Data Ekskul Doble

### ISSUE THREAD

**Issue by rendy43** [eraporsmk/erapor6#62]
![image](https://user-images.githubusercontent.com/119026620/205416632-3eb249d8-3d45-4156-84a8-3ab709c7bbda.png)

Hasil Cetak Rapor data Ekskul Doble, sepertinya nilai dari kelas lain @masadi @eraporsmk

**Comment by eraporsmk** [comment]
Silahkan di update ke versi 6.0.1 pak, dan lakukan Reset Nilai Ekskul melalui login pembina ekskulnya.

Terima Kasih

**Comment by imammh** [comment]
Pak @rendy43 jika sudah teratasi, silahkan di close

**Comment by merzakk** [comment]
Kelas XI yg sudah tidak mengikuti ektra, masih muncul pak

**Comment by imammh** [comment]
> Kelas XI yg sudah tidak mengikuti ektra, masih muncul pak

Silahkan di update ke versi 6.0.1 pak, dan lakukan Reset Nilai Ekskul melalui login pembina ekskulnya.

**Comment by rendy43** [comment]
Makasih pak
