### ISSUE TITLE
Penginstallan di VPS

### ISSUE THREAD

**Issue by ndiptra** [eraporsmk/erapor6#65]
![image](https://user-images.githubusercontent.com/117172868/205487203-d6ac9edf-6be6-498f-a57c-d50b4935bcde.png)

saat melakukan composer update

**Comment by ozonerik** [comment]
biasanya pengaturan databaenya belum diatur di file env nya, atau tidak konek ke databasenya,

**Comment by is33p0wer** [comment]
Mgkn driver php extension pgsql blm diinstall
