### ISSUE TITLE
COUNT JML PESERTA DIDIK DINILAI MAPEL AGAMA BELUM DINILAI SUDAH TERHITUNG

### ISSUE THREAD

**Issue by a-alrizky-a** [eraporsmk/erapor6#66]
![image](https://user-images.githubusercontent.com/119268010/205491954-ae6608cc-2ef1-464e-8239-03db30c7ed5b.png)
Mohon untuk di update lagi TIM Pengembang karen belum melakukan penilaian pada mapel AGAMA namun sudah terhitung dinilai

Terimakasih

**Comment by masadi** [comment]
fixed

**Comment by a-alrizky-a** [comment]
Siap makasih pak
