### ISSUE TITLE
[Kasus di eRapor v6.0.1] Tampilan Ekskul di Menu Wali Kelas Double (Kelas XI dan XII)

### ISSUE THREAD

**Issue by rendy43** [eraporsmk/erapor6#67]
![image](https://user-images.githubusercontent.com/119026620/205544639-14da53c3-1d9d-49bd-ba0b-59cc6ce66274.png)

Mohon atensinya admin, saya sudah update v6.0.1, untuk pengisian nilai Ekskul sudah tidak ada masalah sejak ada tombol reset nilai ekskul, tapi sedikit masih tersisa masalahnya di tampilan menu Ekskul Wali Kelas, kebetulan di sekolah saya ada 3 Ekskul.. Untuk di Kelas X sudah benar yang muncul di menu Ekskul Walas ada 3 nama ekskul, tapi di Kelas XI yang muncul 8 (dengan nama Ekskul double) dimana seharusnya tetap 3 karena yg menurut sy nilai ekskul yg muncul adalah per semester bukan selama siswa aktif sbg siswa, begitupun di Kelas XII juga muncul 11 nama Ekskul dmn seharusnya ttp 3, mmg tidak terlalu mengganggu penilaian, tapi cukup membingungkan saja.

Haturnuhun @eraporsmk @masadi

**Comment by masadi** [comment]
fixed
