### ISSUE TITLE
[Kasus di eRapor v6.0.1 K-13 Revisi] Tujuan Pembelajaran Yang Diinput Untuk Kelas X tapi yang Tampil di "Nilai Akhir" Berubah Untuk Semua Tingkat

### ISSUE THREAD

**Issue by rendy43** [eraporsmk/erapor6#73]
![image](https://user-images.githubusercontent.com/119026620/205821702-10acc0e2-1393-4dfd-98a7-0f156bdf113e.png)

Lapor YTH. admin,
Tujuan Pembelajaran Yang Diinput Untuk Kelas X tapi yang Tampil di "Input Nilai AKhir" Untuk Semua Tingkat, Misalnya di sini Mapel PAI, Akibatnya Tujuan Pembelajaran yg muncul di "Nilai Akademik > Input Nilai Akhir" juga tampil semua kelas X, XI dan XII. Bisa dibayangkan kalau muncul semua kelas bisa banyak dan bingung memilihnya Guru. Seharusnya jika Guru ingin mengisi Nilai Akhir Kelas XII maka Tujuan Pembelajaran yang muncul juga Khusus utk kelas XII bukan semua kelas. Punten belepotan, semoga bisa dipahami ya admin. Nuhun @masadi  @eraporsmk 
 
![image](https://user-images.githubusercontent.com/119026620/205822648-457426aa-d26f-47d3-9856-64d2e3c13586.png)

**Comment by masadi** [comment]
Baik terima kasih pak.
Akan kita telaah ulang.
Karena jika ber-induk pada KD, maka bisa untuk kelas tertentu dan bisa multi kelas (tingkat)
