### ISSUE TITLE
Cetak Rapor Halaman Depan ...

### ISSUE THREAD

**Issue by Didik-Suryanto** [eraporsmk/erapor6#74]
<img width="1074" alt="Screenshot 2022-12-06 at 1 00 11 PM" src="https://user-images.githubusercontent.com/118573236/205832487-3370f949-4575-49eb-a08a-1c624632b5ec.png">

Seperti ini bagaimana nggih, solusinya ..?

**Comment by imammh** [comment]
> inggih terima kasih ... sudah terselesaikan dengan cara logo aslinya saya edit, saya replace dengan logo sekolah dengan image size aslinya ...

Silahkan di close kalau sudah terselesaikan
