### ISSUE TITLE
Capaiaan kompetensi muncul semua pada saat input nilai akhir (akan menceklist CP kelas 12, tetapi CP kelas X dn XI juga muncul)

### ISSUE THREAD

**Issue by idSarmen** [eraporsmk/erapor6#75]
![Screenshot 2022-12-06 164142](https://user-images.githubusercontent.com/49184302/205875903-605385cb-067c-423b-911c-180d8b4c1513.png)
![Screenshot 2022-12-06 164205](https://user-images.githubusercontent.com/49184302/205875915-bbecfd34-98b4-4f77-b03e-9730a22f591d.png)

**Comment by masadi** [comment]
Duplikat #73
