### ISSUE TITLE
Migration db di VPS

### ISSUE THREAD

**Issue by ndiptra** [eraporsmk/erapor6#78]
saat melakukan perintah php artisan migrate

![image](https://user-images.githubusercontent.com/117172868/206085033-39bed3c7-d514-4787-86be-d3da1508a225.png)

**Comment by hid0** [comment]
tulisannya database exists berarti sudah ada, yang lama dihapus dulu baru diimport yang dari database migration erapor dijalankan:)

**Comment by ndiptra** [comment]
kalau dihapus nanti malah gini

![image](https://user-images.githubusercontent.com/117172868/206741899-3c32ec25-feb2-4637-94e8-2ec29ac44faa.png)

**Comment by hendri2212** [comment]
apakah ini sudah solved ? Saya juga mengalami hal yang sama. Padahal sudah pakai php artisan migrate:fresh
harusnya dengan migrate fresh semua table akan di hapus baru di create ulang. Tapi tetap saja database exists

**Comment by hendri2212** [comment]
alhamdulillah solved, setelah drop schema ref
