### ISSUE TITLE
Icon Tombol Keluar Aplikasi Sepertinya Kurang Pas

### ISSUE THREAD

**Issue by ozonerik** [eraporsmk/erapor6#8]
Icon Tombol Keluar Aplikasi Sepertinya Kurang Pas
![tombol keluar aplikasi salah icon](https://user-images.githubusercontent.com/49719997/202743978-51d6e319-ab57-4d65-bea2-a9c819da6c48.jpg)

**Comment by hid0** [comment]
![image](https://user-images.githubusercontent.com/20245892/202917408-69833bc3-9dbe-4d42-b490-48bb99bb6bb9.png)
sudah diganti pak

**Comment by ozonerik** [comment]
versi berapa pa?

**Comment by ozonerik** [comment]
sip berhasil pa, memakai perintah: git pull origin main
