### ISSUE TITLE
Deskripsi Capaian Pembelajaran Tidak Muncul di Rapor Siswa

### ISSUE THREAD

**Issue by Irham82** [eraporsmk/erapor6#83]
![image](https://user-images.githubusercontent.com/68411024/206331647-01dbdec3-1421-4a75-b97f-788f2a544d31.png)
Kenapa yang Deskripsi Capaian Kompetensi tidak Muncul di Raport

**Comment by idSarmen** [comment]
Coba dicek lagi CP nya pak, siapa tau ada karaktr yg ngg sesuai.  CP juga bisa diedit sebelum simpan
