### ISSUE TITLE
gagal cetak raport sebagian siswa

### ISSUE THREAD

**Issue by susmudioko** [eraporsmk/erapor6#85]
cetak raport tidak 100% data bisa di download, ada sebagian siswa yang saat di download raport nya error  500 tp sebagian besar siswa bisa

dan error 500 hanya cetak raport akademik saja,, untuk cetak halaman depan, p5 dan dokumen pendukung lancar

**Comment by herismk** [comment]
Kok blm ada yang bisa jawab yaa? Nungguin juga.

**Comment by susmudioko** [comment]
Git pull origin
