### ISSUE TITLE
Pengambilan data dari Dapodik gagal

### ISSUE THREAD

**Issue by impeesa182** [eraporsmk/erapor6#9]
mengambil data rombel, pesdik aktif, pesdik keluar serta pembelajaran selalu gagal

![image](https://user-images.githubusercontent.com/54379803/202753690-3b48302b-80d2-4ca4-bf46-816cd0c9c3ba.png)

**Comment by ozonerik** [comment]
coba max_execution_time di php.ini nya dibesarkan nilainya menjadi 600, defaultnya 30

**Comment by imammh** [comment]
Bagaimana pak @impeesa182 sudah berhasilkah ?

**Comment by ozonerik** [comment]
jika sudah solved masalahnya jangan lupa klik
![image](https://user-images.githubusercontent.com/49719997/203693485-60f5d1ca-2b81-4de4-a183-57b0071a7699.png)

**Comment by eraporsmk** [comment]
Sementara di tutup karena belum ada tindak lanjut

Terima kasih
