### ISSUE TITLE
Mapping Mapel 1 Rombel ngebug tidak bisa disimpan

### ISSUE THREAD

**Issue by WARDI-NURYANTO** [eraporsmk/erapor6#94]
![image](https://user-images.githubusercontent.com/119034175/206620990-2476a05e-5374-489a-8409-6c446dcda49f.png)

Mohon Solusinya??

**Comment by smktelkom-lpg** [comment]
solusinya simpan dulu 1 mapel, setelah itu baru maping lagi.
jadi kesimpulanya harus dipancing dlu 1 mapel

**Comment by WARDI-NURYANTO** [comment]
udah dipancing cuma kelompoknya gx muncul pak

**Comment by rendy43** [comment]
Update ke versi terbaru.

*Tata Cara Update Aplikasi e-Rapor SMK*

1. Pengguna Windows

Pastikan juga sudah menginstall Aplikasi Composer Jika belum silahkan download & install dulu ==> https://getcomposer.org/download/

Pastikan juga sudah menginstall Aplikasi GIT Jika belum silahkan download & install dulu ==> https://git-scm.com/download/win

a. Manual

Buka Command Prompt (CMD) Run as Administrator
Ketik cd C:\eRaporSMK\dataweb [enter]
Ketik git stash [enter]
Ketik git clean -df [enter]
Ketik git pull origin main [enter]. Tunggu sampai proses update file dari github selesai
Ketik composer update [enter]
Ketik php artisan erapor:update. Tunggu sampai proses update versi aplikasi selesai.
Pastikan di akhir informasi di Command Prompt, versi aplikasi sudah berubah
Cek kembali aplikasi e-Rapor SMK, jika ada yang gagal silahkan laporkan ke Tim Helpdesk
b. Menggunakan file .bat

Silahkan download file updater e-Rapor SMK V6.0.1.bat [disin](https://drive.google.com/file/d/1cBZWtlGqv_bgRFa3CJnVCXzpaGVlg1u1/view).
Buka file updater e-Rapor SMK V6.0.1.bat dengan cara klik kanan dan pilih Run as Administartor.
Tunggu sampai proses update versi aplikasi selesai.
