### ISSUE TITLE
JML PESERTA DIDIK DINILAI 0

### ISSUE THREAD

**Issue by smktelkom-lpg** [eraporsmk/erapor6#95]
Jumlah peserta didik dinilai 0, dan ketika input nilai akhir dan capaian kompetensi sudah terisi semua di rapor juga 0
![image](https://user-images.githubusercontent.com/58032251/206626222-2692384b-3eb5-4ffa-ad6f-af8f30d8f15a.png)

**Comment by rendy43** [comment]
Cb update ke [versi terbaru](https://github.com/eraporsmk/erapor6/wiki/Panduan-Update) punya sy aman soalnya.
