### ISSUE TITLE
Penilaian P5

### ISSUE THREAD

**Issue by Kurjum21** [eraporsmk/erapor6#96]
Penilaian P5 pada e-raporSMK 6.0.1 tidak muncul bagaimana solusinya

**Comment by JU5T3N** [comment]
Untuk Penilaian P5 Tema nya hanya muncul 1 saja sedangkan didapodik sudah diisi 3 tema dan itupun random yg muncul dierapornya 
bagaimana solusinya?
![error](https://user-images.githubusercontent.com/102720866/206963326-d2d7c963-0613-4483-9437-9b035a763f73.png)

**Comment by irfansobo2022** [comment]
Juga masih doble pada **Bergotong royong**
![P5doble](https://user-images.githubusercontent.com/118572243/207024147-f101d5dd-eaaf-4153-8a1d-8cb17996a355.png)

**Comment by eraporsmk** [comment]
Sudah diperbaiki di versi 6.0.3

Terima kasih
