### ISSUE TITLE
Capaian Kompetensi tidak berubah

### ISSUE THREAD

**Issue by mawann** [eraporsmk/erapor6#97]
_Erapor versi 6.0.1 for Linux._

Menu > Nilai Akademik > Input Nilai Akhir > Pilih Mata Pelajaran > Isi **SEMUA** Nilai Akhir dan beri checklist Kompetensi Yang Sudah Dicapai > Simpan.

Menu > Capaian Kompetensi > Pilih Mata Pelajaran. Nah, di sini ada keanehan. Pada beberapa kelas, Capaian Kompetensi terisi sesuai yang dichecklist, tapi pada beberapa kelas lain, ada yang sama sekali tidak berubah, walau pun telah dilakukan Reset.

Server lancar. Prosesor tidak sibuk dan RAM tidak terpakai seluruhnya.

**Comment by rendy43** [comment]
Setelah direset, jangan lupa klik SImpan pak.

**Comment by eraporsmk** [comment]
Kami tutup issue nya.
Jika belum bisa, silahkan dibuka kembali.

Terima kasih
