### ISSUE TITLE
Cetak rapor akademik tulisan terpotong

### ISSUE THREAD

**Issue by arieramba** [eraporsmk/erapor6#99]
![image](https://user-images.githubusercontent.com/119829944/206733635-b7cae77b-0727-43e4-aa50-9bd1a5a22f7c.png)
saat akan cetak rapor akademik terpotong, mohon solusinya

**Comment by arieramba** [comment]
terima kasih, sudah bisa mengunakan update git terbaru

**Comment by restupamuji** [comment]
> 

Bagaimana caranya pak
Bisa dijelaskan lebih detail ?
